require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/gigs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Gig. As you add validations to Gig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Gig.create! valid_attributes
      get gigs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      gig = Gig.create! valid_attributes
      get gig_url(gig)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_gig_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      gig = Gig.create! valid_attributes
      get edit_gig_url(gig)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Gig" do
        expect {
          post gigs_url, params: { gig: valid_attributes }
        }.to change(Gig, :count).by(1)
      end

      it "redirects to the created gig" do
        post gigs_url, params: { gig: valid_attributes }
        expect(response).to redirect_to(gig_url(Gig.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Gig" do
        expect {
          post gigs_url, params: { gig: invalid_attributes }
        }.to change(Gig, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post gigs_url, params: { gig: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gig" do
        gig = Gig.create! valid_attributes
        patch gig_url(gig), params: { gig: new_attributes }
        gig.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the gig" do
        gig = Gig.create! valid_attributes
        patch gig_url(gig), params: { gig: new_attributes }
        gig.reload
        expect(response).to redirect_to(gig_url(gig))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        gig = Gig.create! valid_attributes
        patch gig_url(gig), params: { gig: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested gig" do
      gig = Gig.create! valid_attributes
      expect {
        delete gig_url(gig)
      }.to change(Gig, :count).by(-1)
    end

    it "redirects to the gigs list" do
      gig = Gig.create! valid_attributes
      delete gig_url(gig)
      expect(response).to redirect_to(gigs_url)
    end
  end
end
